# Generated by Django 6.0.3 on 2026-05-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва постачальника')),
                ('contact_person', models.CharField(blank=True, help_text='ПІБ контактної особи', max_length=255, verbose_name='Контактна особа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, help_text='Фактична адреса постачальника', verbose_name='Адреса')),
                ('notes', models.TextField(blank=True, help_text='Додаткова інформація про постачальника', verbose_name='Нотатки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='company.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'company'), name='unique_supplier_name_per_company')],
            },
        ),
    ]
