# Generated by Django 6.0.3 on 2026-05-29 15:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва запчастини')),
                ('part_number', models.CharField(blank=True, help_text='Оригінальний номер запчастини/OEM-номер', max_length=100, verbose_name='Артикул')),
                ('manufacturer', models.CharField(blank=True, help_text='Назва виробника запчастини', max_length=255, verbose_name='Виробник')),
                ('unit', models.CharField(choices=[('pc', 'шт'), ('l', 'л'), ('kg', 'кг'), ('m', 'м'), ('set', 'комплект'), ('pack', 'упаковка'), ('other', 'інше')], default='pc', max_length=10, verbose_name='Одиниця виміру')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Закупівельна ціна, грн')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ціна продажу, грн')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Поточна кількість на складі', max_digits=10, verbose_name='Кількість на складі')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='При досягненні цієї кількості бажано замовити додатково', max_digits=10, verbose_name='Мінімальний залишок')),
                ('location', models.CharField(blank=True, help_text='Стелаж/полиця/комірка', max_length=100, verbose_name='Місце на складі')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='company.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Запчастина',
                'verbose_name_plural': 'Запчастини',
                'ordering': ['name'],
            },
        ),
    ]
