# Generated by Django 6.0.3 on 2026-05-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Основний постачальник запчастини', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='suppliers.supplier', verbose_name='Постачальник'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('part_number', 'company'), name='unique_part_number_per_company'),
        ),
    ]
