# Generated by Django 6.0.3 on 2026-05-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity_on_hand',
        ),
        migrations.RemoveField(
            model_name='part',
            name='supplier',
        ),
    ]
