# Generated by Django 6.0.3 on 2026-06-01 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_part_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Поточна кількість на складі. Оновлюється автоматично при оприбуткуванні закупівель.', max_digits=10, verbose_name='Залишок на складі'),
        ),
    ]
