# Generated by Django 6.0.3 on 2026-06-01 15:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('parts', '0004_part_quantity_on_hand'),
        ('purchases', '0002_alter_purchaseorderitem_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Кількість, отримана за цією закупівлею', max_digits=10, verbose_name='Кількість в партії')),
                ('quantity_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Скільки одиниць з цієї партії вже використано в нарядах', max_digits=10, verbose_name='Використано')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Ціна, за якою було придбано запчастину', max_digits=10, verbose_name='Закупівельна ціна за од., грн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оприбуткування')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_lots', to='company.company', verbose_name='Компанія')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='parts.part', verbose_name='Запчастина')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='purchases.purchaseorderitem', verbose_name='Позиція закупівлі')),
            ],
            options={
                'verbose_name': 'Партія запчастин',
                'verbose_name_plural': 'Партії запчастин',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['part', 'company'], name='parts_partl_part_id_156fcb_idx')],
            },
        ),
    ]
