# Generated by Django 6.0.3 on 2026-05-30 07:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0001_initial'),
        ('parts', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Автоматично згенерований номер замовлення', max_length=50, verbose_name='Номер замовлення')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('ordered', 'Замовлено'), ('partially_received', 'Частково отримано'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], default='draft', max_length=30, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Додаткова інформація про замовлення', verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='company.company', verbose_name='Компанія')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='accounts.employee', verbose_name='Створив')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Замовлення закупівлі',
                'verbose_name_plural': 'Замовлення закупівлі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, help_text='Кількість замовлених одиниць', max_digits=10, verbose_name='Замовлено')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Кількість фактично отриманих одиниць', max_digits=10, verbose_name='Отримано')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Закупівельна ціна за одиницю', max_digits=10, verbose_name='Ціна за одиницю, грн')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='parts.part', verbose_name='Запчастина')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('order_number', 'company'), name='unique_order_number_per_company'),
        ),
    ]
