# Generated by Django 6.0.3 on 2026-05-30 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='part',
            field=models.ForeignKey(help_text='Запчастина, яку неможливо видалити, якщо вона є в прихідних накладних', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='parts.part', verbose_name='Запчастина'),
        ),
    ]
