# Generated by Django 6.0.3 on 2026-06-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employee_role'),
        ('company', '0001_initial'),
        ('purchases', '0002_alter_purchaseorderitem_part'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сума платежу в гривнях', max_digits=12, verbose_name='Сума, грн')),
                ('payment_date', models.DateField(db_index=True, verbose_name='Дата оплати')),
                ('payment_type', models.CharField(choices=[('cash', 'Готівка'), ('bank_transfer', 'Банківський переказ'), ('card', 'Картка'), ('other', 'Інше')], default='bank_transfer', max_length=20, verbose_name='Спосіб оплати')),
                ('notes', models.TextField(blank=True, help_text='Призначення платежу, номер рахунку тощо', verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='company.company', verbose_name='Компанія')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to='accounts.employee', verbose_name='Створив')),
                ('purchase_order', models.ForeignKey(blank=True, help_text="Замовлення, за яке здійснюється оплата (необов'язково)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchases.purchaseorder', verbose_name='Замовлення')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Платіж постачальнику',
                'verbose_name_plural': 'Платежі постачальникам',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['supplier', 'payment_date'], name='purchases_s_supplie_1bd89c_idx'), models.Index(fields=['company', 'payment_date'], name='purchases_s_company_20ddf4_idx')],
            },
        ),
    ]
