# Generated by Django 6.0.3 on 2026-06-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікується'), ('completed', 'Проведено'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
