# Generated by Django 6.0.3 on 2026-06-03 14:07

from django.db import migrations, models


def backfill_payment_numbers(apps, schema_editor) -> None:
    """Присвоює номери PAY-XXXXX існуючим платежам."""
    SupplierPayment = apps.get_model('purchases', 'SupplierPayment')
    Company = apps.get_model('company', 'Company')

    for company in Company.objects.all():
        payments = SupplierPayment.objects.filter(company=company).order_by('id')
        for idx, payment in enumerate(payments, start=1):
            payment.payment_number = f'PAY-{idx:05d}'
            payment.save(update_fields=['payment_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employee_role'),
        ('company', '0001_initial'),
        ('purchases', '0004_supplierpayment_status'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_number',
            field=models.CharField(
                blank=True,
                help_text='Автоматично згенерований номер платежу',
                max_length=50,
                verbose_name='Номер платежу',
            ),
        ),
        migrations.RunPython(
            backfill_payment_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(
                fields=('payment_number', 'company'),
                name='unique_payment_number_per_company',
            ),
        ),
    ]
