# Generated by Django 6.0.3 on 2026-06-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_employee_labor_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Унікальний ідентифікатор модуля (companies, workorders, …)', max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Людиночитана назва модуля (Компанії, Наряди, …)', max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, help_text="Необов'язковий опис модуля", verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модулі',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=False, verbose_name='Читання')),
                ('can_create', models.BooleanField(default=False, verbose_name='Створення')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Редагування')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Видалення')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.module', verbose_name='Модуль')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Право ролі',
                'verbose_name_plural': 'Права ролей',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
