# Generated by Django 6.0.3 on 2026-06-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_employee_labor_percent_and_more'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=False, verbose_name='Читання')),
                ('can_create', models.BooleanField(default=False, verbose_name='Створення')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Редагування')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Видалення')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.employee', verbose_name='Співробітник')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='permissions.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Право співробітника',
                'verbose_name_plural': 'Права співробітників',
                'unique_together': {('employee', 'module')},
            },
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
