# Generated by Django 6.0.3 on 2026-05-29 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('manager', 'Менеджер'), ('mechanic', 'Майстер'), ('accountant', 'Бухгалтер'), ('admin', 'Адміністратор')], default='mechanic', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company', verbose_name='Компанія')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company')],
            },
        ),
    ]
