# Generated by Django 6.0.3 on 2026-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('manager', 'Менеджер'), ('mechanic', 'Майстер'), ('accountant', 'Бухгалтер'), ('admin', 'Адміністратор'), ('purchaser', 'Закупівельник'), ('storekeeper', 'Складовщик')], default='mechanic', max_length=20, verbose_name='Роль'),
        ),
    ]
