# Generated by Django 6.0.3 on 2026-06-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Унікальний ідентифікатор ролі (director, manager, ...)', max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Людиночитана назва ролі (Директор, Менеджер, ...)', max_length=50, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Ролі',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Тимчасове поле для міграції даних.', max_length=20, verbose_name='Роль (застаріле)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.role', verbose_name='Ролі'),
        ),
    ]
