# Generated by Django 6.0.3 on 2026-06-03 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employee_labor_percent_employee_parts_sale_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='labor_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Відсоток від вартості виконаних робіт, який нараховується співробітнику', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Відсоток від робіт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='parts_sale_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Відсоток від вартості проданих запчастин, який нараховується співробітнику', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Відсоток від продажу запчастин'),
        ),
    ]
