# Generated by Django 6.0.3 on 2026-06-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employee_labor_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='labor_percent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='parts_sale_percent',
        ),
    ]
