# Generated by Django 6.0.3 on 2026-05-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(help_text='17 символів, унікальний в межах компанії', max_length=17, verbose_name='VIN-код')),
                ('brand', models.CharField(db_index=True, max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електрика'), ('hybrid', 'Гібрид'), ('gas', 'Газ')], default='petrol', max_length=20, verbose_name='Тип двигуна')),
                ('engine_displacement', models.DecimalField(blank=True, decimal_places=1, help_text='У літрах (напр. 2.0). Для електромобілів — порожньо', max_digits=4, null=True, verbose_name="Об'єм двигуна, л")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='company.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('vin_code', 'company'), name='unique_vin_per_company')],
            },
        ),
    ]
