# Generated by Django 6.0.3 on 2026-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin_code',
            field=models.CharField(db_index=True, help_text='17 символів, унікальний в межах компанії', max_length=17, verbose_name='VIN-код'),
        ),
    ]
