# Generated by Django 6.0.3 on 2026-06-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0002_alter_vehicle_vin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Клієнт-власник автомобіля (необов'язково)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='clients.client', verbose_name='Власник'),
        ),
    ]
