# Generated by Django 6.0.3 on 2026-05-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва роботи')),
                ('description', models.TextField(blank=True, help_text='Детальний опис роботи', verbose_name='Опис')),
                ('category', models.CharField(choices=[('repair', 'Ремонт'), ('maintenance', 'ТО'), ('diagnostics', 'Діагностика'), ('electrical', 'Електрика'), ('bodywork', 'Кузовні роботи'), ('tyre', 'Шиномонтаж'), ('detailing', 'Детейлінг'), ('other', 'Інше')], default='other', max_length=30, verbose_name='Категорія')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktypes', to='company.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Вид роботи',
                'verbose_name_plural': 'Види робіт',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'company'), name='unique_worktype_name_per_company')],
            },
        ),
    ]
