# Generated by Django 6.0.3 on 2026-06-11 18:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Стандартна вартість роботи (підставляється при створенні наряду)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Вартість за замовчуванням, грн'),
        ),
    ]
