# Generated by Django 6.0.3 on 2026-05-30 08:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0001_initial'),
        ('parts', '0003_remove_part_purchase_price_and_more'),
        ('vehicles', '0002_alter_vehicle_vin_code'),
        ('worktypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В роботі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='company.company', verbose_name='Компанія')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='accounts.employee', verbose_name='Створив')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='vehicles.vehicle', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Заказ-наряди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Кількість')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за од., грн')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_parts', to='parts.part', verbose_name='Запчастина')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workorders.workorder', verbose_name='Заказ-наряд')),
            ],
            options={
                'verbose_name': 'Запчастина в наряді',
                'verbose_name_plural': 'Запчастини в наряді',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Кількість (нормо-годин)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за од., грн')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Опис')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services', to='accounts.employee', verbose_name='Виконавець')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workorders.workorder', verbose_name='Заказ-наряд')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_services', to='worktypes.worktype', verbose_name='Вид роботи')),
            ],
            options={
                'verbose_name': 'Робота в наряді',
                'verbose_name_plural': 'Роботи в наряді',
            },
        ),
    ]
