# Generated by Django 6.0.3 on 2026-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Пробіг автомобіля на момент створення наряду', null=True, verbose_name='Пробіг, км'),
        ),
    ]
