# Generated by Django 6.0.3 on 2026-06-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_partlot'),
        ('workorders', '0002_workorder_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpart',
            name='part_lot',
            field=models.ForeignKey(blank=True, help_text='Партія запчастин, з якої взято цю одиницю. Потрібна для розрахунку прибутку.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_parts', to='parts.partlot', verbose_name='Партія закупівлі'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна закупівлі на момент створення рядка (копія з PartLot)', max_digits=10, null=True, verbose_name='Закупівельна ціна за од., грн'),
        ),
    ]
