# Generated by Django 6.0.3 on 2026-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorderpart_part_lot_workorderpart_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В роботі'), ('completed', 'Завершено'), ('awaiting_payment', 'Очікує оплати'), ('cancelled', 'Скасовано')], default='draft', max_length=30, verbose_name='Статус'),
        ),
    ]
