# Generated by Django 6.0.3 on 2026-06-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_split_client_name'),
        ('workorders', '0004_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Клієнт за нарядом (може відрізнятися від власника авто)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='clients.client', verbose_name='Клієнт'),
        ),
    ]
